Feature chat
JoeRoussy/roomie pull request #13
Opened 2018-01-29 02:44 UTC by aleechan

Added the visual layout and front-end functions for a basic chat. The user information sidebar in the chat can be implemented when we figure out what will go there.

2018-02-01 18:11 UTC, JoeRoussy requested changes

2018-02-01 18:11 UTC, JoeRoussy commented on client/react/components/chat/channelBar.jsx
> +const listChannels = ({
Put this inside the main render method we we don't need to pass in all these variables.

We are going to try and have logic in the render method before the return.

This means the render method can't have an implicit return.

2018-02-01 18:11 UTC, JoeRoussy commented on client/react/components/chat/chatView.jsx
> +        <Comment key= {i}>
Indent this 1 level

2018-02-01 18:11 UTC, JoeRoussy commented on client/react/components/chat/chatView.jsx
> +                <Comment.Author as='a'>{message.userName}</Comment.Author>
We should implement a 'go to profile'.

Something like a link to /profile/{id}

2018-02-01 18:11 UTC, JoeRoussy commented on client/redux/reducers/chatReducer.jsx
> +            state = {...state,activeChannel: actions.payload.channel.name}
Break into different lines to it is easier to read:

```
state = {
    ...state,
    activeChannel: actions.payload.channel.name
}
```

2018-02-01 18:11 UTC, JoeRoussy commented on client/redux/reducers/chatReducer.jsx
> +                    state = {...state, chatLog: Channel1Chat};
Same as above for all these examples below

2018-02-01 19:55 UTC, JugesPatel reviewed
Overall it looks good. Agree with comments that Joe made.

2018-02-04 04:08 UTC, JoeRoussy approved these changes

2018-02-04 04:08 UTC, merged